apiVersion: v1
kind: Service
metadata:
  name: k8s-test
  labels:
    app: k8s-centos8-deployment
spec:
  selector:
    app: k8s-centos8-deployment
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
